{
    "0": "Assassin's Bullet \"Speed Strike\"",
    "2": "Bullet Sign \"Eagle Shooting\"",
    "5": "Bullet Sign \"The Eagle Has Shot Its Target\"",
    "6": "Gun Sign \"Lunatic Gun\"",
    "9": "Gun Sign \"Lunatic Gun\"",
    "10": "Rabbit Sign \"Strawberry Dango\"",
    "12": "Rabbit Sign \"Berry Berry Dango\"",
    "14": "Rabbit Sign \"Dango Influence\"",
    "18": "Moon-Viewing \"September Full Moon\"",
    "21": "Moon-Viewing Saké \"Lunatic September\"",
    "22": "Dream Sign \"Scarlet Nightmare\"",
    "24": "Dream Sign \"Scarlet Oppressive Nightmare\"",
    "26": "Dream Sign \"Indigo Dream of Anxiety\"",
    "28": "Dream Sign \"Indigo Three-Layered Dream of Anxiety\"",
    "29": "Dream Sign \"Eternally Anxious Dream\"",
    "30": "Dream Sign \"Ochre Confusion\"",
    "32": "Dream Sign \"Ochre Labyrinthine Confusion\"",
    "34": "Dream Sign \"Dream Catcher\"",
    "36": "Dream Sign \"Azure Dream Catcher\"",
    "37": "Dream Sign \"Losing Oneself in a Dream\"",
    "38": "Moon Sign \"Ultramarine Lunatic Dream\"",
    "42": "Orb Sign \"Pondering...\"",
    "44": "Orb Sign \"Group Pondering...\"",
    "46": "Orb Sign \"Brainrot Detection Mines\"",
    "48": "Orb Sign \"Brainrot Detection Mines V2\"",
    "50": "Pondering Sign \"Þē Golden Orb\"",
    "52": "Pondering Sign \"Þē Shining Golden Orb\"",
    "54": "\"One-Winged YTP Hero\"",
    "58": "Soldier \"Moon-Shaped Box!\"",
    "60": "Soldier \"Maggots!\"",
    "62": "Circus \"Bro Has Officially Lost It\"",
    "64": "American \"Red-Blooded American Memes\"",
    "66": "Revengence \"Stop Those Bullets!\"",
    "69": "Revengence \"Rules of Nature\"",
    "70": "Elite Memes \"American-Striped Hellscape\"",
    "74": "\"Toxic Memes\"",
    "76": "\"Meme Culture is Dead\"",
    "78": "\"Purified Memes of the Internet\"",
    "82": "\"john-cena-bing-chilling.mp3\"",
    "86": "\"deez-nuts-got-eem.mp3\"",
    "88": "\"imma-put-my-cat-on-the-mic.mp3\"",
    "90": "\"metal-pipe-falling-sound.mp3\"",
    "94": "\"moms-spaghetti.mp3'\"",
    "98": "\"drip-goku.mp3\"",
    "101": "\"gay-moan.mp3\"",
    "102": "Purified Memes \"Whereabouts of the Balls\"",
    "104": "Purified Memes \"Return to Greatness in Memes\"",
    "106": "Butterfly \"Butterfly Supplantation\"",
    "107": "Super-Express \"Dream Express\"",
    "108": "Crawling Dream \"Creeping Bullet\"",
    "109": "Otherworld \"Oumagatoki\"",
    "110": "Earth \"Impurity Within One's Body\"",
    "111": "Moon \"Apollo Reflection Mirror\"",
    "112": "\"Shitpost for Killing a Medieval Peasant\"",
    "113": "Otherworld \"Hell's Non-Ideal Danmaku\"",
    "114": "Earth \"Rain Falling in Hell\"",
    "115": "Moon \"Lunatic Impact\"",
    "116": "\"Pristine Danmaku for Killing a Person\"",
    "117": "\"Trinitarian Rhapsody\"",
    "118": "\"First and Last Nameless Danmaku\"",
    "45": "Orb Sign \"100 Percent Orb Pondered!\""
}
