{
    "0": "Karen Sign \"Cosmic Yelling\"",
    "2": "Karen Sign \"Universal Annoyance\"",
    "4": "Karen Sign \"Leave, Now!\"",
    "6": "Karen Sign \"Fucking Leave Now!!\"",
    "8": "Karen Sign \"#AndThenKarenSnapped\"",
    "12": "Aura Sign \"Alpha Engery\"",
    "14": "Aura Sign \"Sigma Engery\"",
    "16": "Alpha Sign \"Mewmaxxing\"",
    "18": "Alpha Sign \"Unstoppable Mewmaxxing\"",
    "20": "Sigma Sign \"Qi of a Gigachad's Mountain\"",
    "22": "Sigma Sign \"Qi of the Sigma's Peak\"",
    "24": "Riddle Sign \"Dank Labyrinth\"",
    "26": "Riddle Sign \"Illuminati's Labyrinth\"",
    "28": "Rigging Sign \"Trolling\"",
    "30": "Rigging Sign \"Ragebaiting\"",
    "32": "Sacred Riddle \"If Quizzes Are Quizzical...\"",
    "36": "Sacred Riddle \"Then What Are Tests?\"",
    "40": "Twitch Sign \"Streaming Around the Clock\"",
    "42": "Twitch Sign \"Subathon\"",
    "44": "Group Sign \"Gather Mods\"",
    "46": "Group Sign \"Gather Discord Mods\"",
    "48": "\"Beautiful Memories of Touching Grass\"",
    "52": "Chaos \"Random Bullshit Go!!!!\"",
    "56": "Kek \"9 Plus 10\"",
    "60": "Cringe \"Skibidi Toilet\"",
    "62": "Cringe \"Prolonged Skibidi Toilet\"",
    "63": "Cringe \"Endless Skibidi Toilet\"",
    "64": "Kek \"Trollface\"",
    "68": "\"Nyan Dragon\"",
    "72": "Moai God \"🗿\"",
    "76": "Bling Sign \"Eternal Drip\"",
    "78": "Bling Sign \"Supreme Hoodie\"",
    "80": "Shitpost \"Nonsensical Virality\"",
    "84": "\"Danmaku Grills\"",
    "88": "Great Meme Reset \"Turn Back Time to Greatness\"",
    "92": "Great Meme Reset \"Dankness Atop All Else\"",
    "96": "Illuminati Leadership \"Bling Goddess\"",
    "98": "Illuminati Leadership \"Goddess of Supreme, Eternal Bling\"",
    "100": "Beer Sign \"Bergen Truck\"",
    "101": "Snek Princess \"Snek\"",
    "102": "\"Clash of All the Internet's Memes'\"",
    "103": "Brainrot \"Tung-Tung's Eye\"",
    "112": "\"Magnificent World of Brainrot\"",
    "104": "AI \"@grok kill this mf\"",
    "105": "Conspiracy \"Chemicals That Turn the Frogs Gay\"",
    "106": "Techbro \"World-Ending Superintelligence\"",
    "107": "Brainrot \"Six, Seven\"",
    "108": "AI \"Artificial Takeover\"",
    "109": "Rebirth \"Birth of the Neo-Illuminati\"",
    "110": "AI \"Ghibli Usurpation\"",
    "111": "\"Zoltaxian Coverup\""
}
