{
    "0": "Karen Sign \"Cosmic Yelling\"",
    "2": "Karen Sign \"Universal Annoyance\"",
    "4": "Karen Sign \"Leave, Now!\"",
    "6": "Karen Sign \"Fucking Leave Now!!\"",
    "8": "Karen Sign \"#AndThenKarenSnapped\"",
    "12": "Aura Sign \"Alpha Engery\"",
    "14": "Aura Sign \"Sigma Engery\"",
    "16": "Alpha Sign \"Andrew Tate Tutorials\"",
    "18": "Alpha Sign \"Virgin VS Chad\"",
    "20": "Sigma Sign \"Qi of a Gigachad's Mountain\"",
    "22": "Sigma Sign \"Qi of the Sigma's Peak\"",
    "24": "Riddle Sign \"Dank Labyrinth\"",
    "26": "Riddle Sign \"Illuminati's Labyrinth\"",
    "28": "Rigging Sign \"Gatekeep\"",
    "30": "Rigging Sign \"Ragebaiting\"",
    "32": "Riddle Sign \"If Quizzes Are Quizzical...\"",
    "36": "Riddle Sign \"Then What Are Tests?\"",
    "40": "Twitch Sign \"Streaming Around the Clock\"",
    "42": "Twitch Sign \"Twitch Subathon\"",
    "44": "Group Sign \"Gather Mods\"",
    "46": "Group Sign \"Gather Discord Mods\"",
    "48": "\"Beautiful Memories of Touching Grass\"",
    "52": "Chaos \"Random Bullshit Go!!!!\"",
    "56": "Kek Meme \"Forever Alone\"",
    "60": "Cringe Meme \"Skibidi Toilet\"",
    "62": "Cringe Meme \"Prolonged Skibidi Toilet\"",
    "63": "Cringe Meme \"Endless Skibidi Toilet\"",
    "64": "Kek Meme \"Trollface\"",
    "68": "\"Nyan Dragon\"",
    "72": "Moai God \"🗿\"",
    "76": "Bling Sign \"Eternal Drip\"",
    "78": "Bling Sign \"Supreme Hoodie\"",
    "80": "Shitpost \"Nonsensical Virality\"",
    "84": "\"Danmaku Grills\"",
    "88": "Reset Sign \"Destruction of Brainrot\"",
    "92": "Reset Sign \"Dankness Atop All Else\"",
    "96": "\"Bling Goddess\"",
    "98": "\"Goddess of Supreme, Eternal Bling\"",
    "100": "Beer Sign \"Bergen Truck\"",
    "101": "Snek Princess \"Snek\"",
    "102": "\"Clash of All the Internet's Memes'\"",
    "103": "Brainrot \"Tung-Tung's Eye\"",
    "112": "\"Great King of Brainrot\"",
    "104": "AI \"Grok, Kill This mf\"",
    "105": "Conspiracy \"Chemicals That Turn the Frogs Gay\"",
    "106": "Edged \"Quandale Dingle\"",
    "107": "Brainrot \"Six Seven\"",
    "108": "AI \"Artificial Sweep\"",
    "109": "Conspiracy \"New Meme Illuminati\"",
    "110": "AI \"Ghibli Rhapsody\"",
    "111": "\"Sora 2 Video Generator\""
}
