{
    "0": "Ice Sign \"Ultimate Blizzard\"",
    "2": "Water Sign \"Tail Fin Slap\"",
    "6": "Scale Sign \"Scale Wave\"",
    "8": "Scale Sign \"Raging Waves of the Reversed Scale\"",
    "9": "Scale Sign \"Great Raging Waves of the Reversed Scale\"",
    "10": "Flight Sign \"Flying Head\"",
    "14": "Neck Sign \"Close-Eye Shot\"",
    "16": "Neck Sign \"Rokurokubi Flight\"",
    "18": "Flying Head \"Multiplicative Head\"",
    "20": "Flying Head \"Seventh Head\"",
    "21": "Flying Head \"Ninth Head\"",
    "22": "Flying Head \"Dullahan Night\"",
    "26": "Fang Sign \"Moonlit Canine Teeth\"",
    "28": "Transformation \"Triangle Fang\"",
    "30": "Transformation \"Star Fang\"",
    "32": "Roar \"Strange Roar\"",
    "34": "Roar \"Full Moon Howling\"",
    "36": "Wolf Sign \"Star Ring Pounce\"",
    "38": "Sirius \"High-Speed Pounce\"",
    "40": "Heikyoku \"Sounds of Jetavana's Bell\"",
    "44": "Vengeful Spirit \"Hoichi the Earless\"",
    "46": "Vengeful Spirit \"Great Vengeful Spirit of Taira\"",
    "48": "Music Sign \"Wicked Musical Score\"",
    "50": "Music Sign \"Malicious Musical Score\"",
    "51": "Music Sign \"Double Score\"",
    "52": "Koto Sign \"Sounds of Anicca's Koto\"",
    "56": "Echo Sign \"Heian's Reverberation\"",
    "58": "Echo Sign \"Echo Chamber\"",
    "60": "Koto Music \"Social Upheaval Koto Music Dirge\"",
    "62": "Koto Music \"Social Upheaval Requiem\"",
    "64": "Deceit Sign \"Reverse Needle Attack\"",
    "68": "Reverse Sign \"Danmaku Through the Looking-Glass\"",
    "70": "Reverse Sign \"Evil in the Mirror\"",
    "72": "Reverse Sign \"This Side Down\"",
    "74": "Reverse Sign \"Overturning All Under Heaven\"",
    "76": "Reverse Bow \"Dream Bow of Heaven & Earth\"",
    "78": "Reverse Bow \"Decree of the Dream Bow of Heaven & Earth\"",
    "80": "Turnabout \"Reverse Hierarchy\"",
    "82": "Turnabout \"Change Air Brave\"",
    "84": "Goofy Ahh \"Inchling's Memes'\"",
    "86": "Goofy Ahh \"Inchling's Quandale Dingle\"",
    "88": "Hood Classic \"Grow Bigger!\"",
    "90": "Hood Classic \"Grow Even Bigger!\"",
    "92": "Blinged Sword \"Shining Supreme Sword\"",
    "96": "Hood Classic \"You Grow Bigger!\"",
    "100": "\"Attack on Memes\"",
    "102": "\"Wall of Quandale\"",
    "104": "\"Hop-o'-The-Six Seven\"",
    "106": "\"The Seven Quandale-Boshi\"",
    "108": "String Music \"Storm Ensemble\"",
    "109": "String Music \"Joururi World\"",
    "110": "First Bababooey \"Raging Temple Taiko\"",
    "111": "Second Bababooey \"Vengeful Spirit Aya-no-Tsuzumi\"",
    "112": "Third Bababooey \"Three Claps at Midnight\"",
    "113": "Death Bababooey \"Land Percuss\"",
    "114": "Fifth Bababooey \"Ba-Ba Booey\"",
    "115": "Sixth Bababooey \"Ragebaiting\"",
    "116": "Seventh Bababooey \"High Speed White Tear\"",
    "117": "Eighth Bababooey \"Meme God's Anger\"",
    "118": "\"Blue Lady Group\"",
    "119": "\"Pristine Bababooey\""
}
