{
    "0": "Stone Sign \"Stone Woods\"",
    "2": "Stone Sign \"Stone Conifers\"",
    "4": "Stone Sign \"Children's Limbo\"",
    "6": "Stone Sign \"Adult Children's Limbo\"",
    "8": "Stone Sign \"Stone Baby\"",
    "10": "Stone Sign \"Heavy Stone Baby\"",
    "12": "Drowning Sign \"Drowning in the Sanzu\"",
    "16": "Oni Sign \"Demon Siege\"",
    "18": "Oni Sign \"Hungry Demon Siege\"",
    "20": "Water Sign \"Trial of Water Sharing\"",
    "22": "Water Sign \"High-Level Tribulation of Water Sharing\"",
    "23": "Water Sign \"Ultimate Tribulation of Water Sharing\"",
    "24": "Light Sign \"Trial of Land Surveillance\"",
    "26": "Light Sign \"High-Level Tribulation of Land Surveillance\"",
    "27": "Light Sign \"Ultimate Tribulation of Land Surveillance\"",
    "28": "Oni Sign \"Trial of Oni Passage\"",
    "30": "Oni Sign \"High-Level Tribulation of Oni Passage\"",
    "31": "Oni Sign \"Hell-Level Tribulation of Oni Passage\"",
    "32": "Tortoise Sign \"Tortoiseshell Hell\"",
    "36": "Oni Sign \"Beasts Attacking from the Rear\"",
    "38": "Oni Sign \"Mangy Beasts Attacking from the Rear\"",
    "39": "Oni Sign \"Devilish Beasts Attacking from the Rear\"",
    "40": "Dragon Sign \"Dragon Crest Bullets\"",
    "44": "Haniwa \"Archer Haniwa\"",
    "46": "Haniwa \"Skilled Archer Haniwa\"",
    "48": "Haniwa \"Fencer Haniwa\"",
    "50": "Haniwa \"Skilled Fencer Haniwa\"",
    "52": "Haniwa \"Cavalry Haniwa\"",
    "54": "Haniwa \"Skilled Cavalry Haniwa\"",
    "56": "Haniwa \"Hollow Inexhaustible Troops\"",
    "58": "Haniwa \"Undefeated Inexhaustible Troops\"",
    "60": "Square Shape \"Square-Shaped Sculpting Art\"",
    "62": "Square Shape \"Square Creature\"",
    "64": "Circular Shape \"Perfect Circle Sculpting Art\"",
    "66": "Circular Shape \"Circle Creature\"",
    "68": "Linear Shape \"Line-Shaped Sculpting Art\"",
    "70": "Linear Shape \"Linear Creature\"",
    "72": "Haniwa \"Horse-and-Rider Idol Sculpting Art\"",
    "74": "Haniwa \"Idol Creature\"",
    "76": "\"Oni-Shaped Sculpting Art\"",
    "80": "\"Geometric Creature\"",
    "84": "\"Idola Diabolus\"",
    "88": "Bloody Battle \"Watershed of Blood\"",
    "89": "Bloody Battle \"Hell Realm Sight-Line\"",
    "90": "Bloody Battle \"All-Spirit Oniwatari\"",
    "91": "Agile Skill \"Thrilling Shot\"",
    "92": "Agile Skill \"Lightning Neigh\"",
    "93": "Agile Skill \"Dense Crowd\"",
    "94": "Agile Skill \"Beast Epidemicity\"",
    "95": "Agile Skill \"Triangle Chase\"",
    "96": "Agile Skill \"Black Pegasus Meteor Shot\"",
    "97": "Agile Skill \"Muscle Explosion\"",
    "98": "\"Follow Me, Unafraid\"",
    "99": "\"Oni-Shaped Hoi Polloi\"",
    "100": "\"Deeds of Devilish Beasts\""
}