{
    "0": "Beckon Sign \"Danmaku Business Boom\"",
    "4": "Beckon Sign \"Shoot Away Disaster, Beckon in Fortune\"",
    "8": "Forest Sign \"Tree-Veiling Technology\"",
    "10": "Forest Sign \"Extreme Tree-Veiling Technology\"",
    "11": "Forest Sign \"True Tree-Veiling Technology\"",
    "12": "Forest Sign \"Innermost Forest Region\"",
    "14": "Forest Sign \"Extreme Innermost Forest Region\"",
    "15": "Forest Sign \"True Innermost Forest Region\"",
    "16": "Leaf Skill \"Green Spiral\"",
    "18": "Leaf Skill \"Green Cyclone\"",
    "19": "Leaf Skill \"Green Tornado\"",
    "20": "Mountain Sign \"Heaven-Shaking Kumomagusa\"",
    "22": "Mountain Apparition \"Astonishing Kumomagusa\"",
    "24": "Mountain Sign \"Usuyukisou Shining with Bewitching Light\"",
    "26": "Mountain Apparition \"Usuyukisou of Thronging Crowds of Youma\"",
    "28": "Mountain Flower \"Komakusa of Massacre\"",
    "30": "Mountain Flower \"Mountain Queen of Massacre\"",
    "32": "Orb Sign \"Rainbow Dragon Yin-Yang Orbs\"",
    "35": "Orb Sign \"Yin-Yang Divine Orbs\"",
    "40": "\"Yin-Yang Suffocation\"",
    "36": "Jeweled General \"Queen of Yin-Yang Sphere\"",
    "38": "Queenly Gem \"Beyond the Rainbow Door\"",
    "68": "\"Meme Market\"",
    "70": "\"High Quality Meme Market\"",
    "71": "\"Cringe Free Market\"",
    "76": "\"Shitpost Dominion\"",
    "78": "\"Dubious Shitpost Dominion\"",
    "79": "\"Disbolical Shitpost Dominion\"",
    "92": "Vintage Story \"Temporal Storm System\"",
    "91": "Terraria \"Nuclear Celebration MKII\"",
    "90": "Minecraft \"Ever-Accumulating Redstone Dump\"",
    "87": "Soulsborne \"Defence of Lost Izalith\"",
    "88": "Deep Rock \"Glyphid Swarms\"",
    "89": "Ultrakill \"Unparryable Sky Snakes\"",
    "93": "Metal Gear \"Snake Eater\"",
    "94": "Skyrim \"Dragonborn\"",
    "95": "\"420 Noscope Blazer\"",
    "96": "\"Himemushi-sama's Uncountable Gaming Feats\"",
    "80": "\"Asylum of Danmaku\"",
    "84": "False Drip \"Yankee With No Brim\"",
    "85": "Trickshot \"The Kuda-gitsune's Fantastic Noscope Montage'\"",
    "60": "\"30 Dollar Danmaku\"",
    "44": "Calamitous Star \"Dance of Star-Sparked Wildfire\"",
    "46": "Calamitous Star \"Wild Dance of Star-Sparked Wildfire\"",
    "48": "Stellar Wind \"Dance of Dazzling Iridescence\"",
    "50": "Stellar Wind \"Wild Dance of Dazzling Iridescence\"",
    "56": "Rainbow Illumination \"Clear and Tranquil Wind and Moon\"",
    "52": "Luminous Horse \"Dance of Sky-Racing Heavenly Steeds\"",
    "54": "Luminous Horse \"Wild Dance of Sky-Racing Heavenly Steeds\"",
    "86": "Fox Sound \"The Everlasting Mystery of the Sounds of Foxes\"",
    "64": "\"Danmaku Hoarder's Obsession\"",
    "72": "\"Rainbow Ring of People\""
}
