{
    "0": "Karen Sign \"Cosmic Yelling\"",
    "2": "Karen Sign \"Universal Annoyance\"",
    "4": "Karen Sign \"Leave, Now!\"",
    "6": "Karen Sign \"Fucking Leave Now!!\"",
    "8": "Karen Sign \"#AndThenKarenSnapped\"",
    "12": "Aura Sign \"Hammertime!\"",
    "14": "Aura Sign \"U Can't Touch Dis\"",
    "16": "Alpha Sign \"Daily Juicy Memes\"",
    "18": "Alpha Sign \"Bro Just Pack it Up\"",
    "20": "Sigma Sign \"Qi of a Gigachad Mountain\"",
    "22": "Sigma Sign \"Qi of Sigma Peak\"",
    "24": "Riddle Sign \"Illuminati's Labyrinth\"",
    "26": "Riddle Sign \"Barry, 63, Labyrinth\"",
    "28": "Obstructing Sign \"Gatekeep\"",
    "30": "Obstructing Sign \"I Will Build a Great Wall\"",
    "32": "Riddle Sign \"If Quizzes Are Quizzical, Then What Are Tests\"",
    "36": "Lebron Sign \"You Are My Sunshine\"",
    "40": "Twitch Sign \"Streaming Around the Clock\"",
    "42": "Twitch Sign \"Twitch Subathon\"",
    "44": "Group Sign \"Gather Mods\"",
    "46": "Group Sign \"Gather Discord Mods\"",
    "48": "\"Beautiful Memories of Touching Grass\"",
    "52": "Chaos \"Random Bullshit Go!!!!\"",
    "56": "Kek Meme \"Forever Alone\"",
    "60": "Cringe Meme \"Skibidi Toilet\"",
    "62": "Cringe Meme \"Prolonged Skibidi Toilet\"",
    "63": "Cringe Meme \"Endless Skibidi Toilet\"",
    "64": "Kek Meme \"Trollface\"",
    "68": "\"Nyan Dragon\"",
    "72": "Moai God \"🗿\"",
    "76": "Bling Sign \"Eternal Drip\"",
    "78": "Bling Sign \"Supreme Hoodie\"",
    "80": "Shitpost \"Nonsensical Virality\"",
    "84": "\"Danmaku Grills\"",
    "88": "Reset Sign \"Destruction of Brainrot\"",
    "92": "Reset Sign \"Dankness Atop All Else\"",
    "96": "\"Bling Goddess\"",
    "98": "\"Goddess of Supreme, Eternal Bling\"",
    "100": "Beer Sign \"Bergen Truck\"",
    "101": "Snek Princess \"Snek\"",
    "102": "\"Clash of All the Internet's Memes'\"",
    "103": "Truth \"Tetra Mono-Eye\"",
    "112": "\"Great King of Angolmois\"",
    "104": "Truth \"Old Illuminati\"",
    "105": "Truth \"Chemtrail Cloud\"",
    "106": "Truth \"Reptilian Intelligence\"",
    "107": "Truth \"Flat Earther\"",
    "108": "Truth \"Artificial Disaster\"",
    "109": "Truth \"New World Order\"",
    "110": "Truth \"Tartarian Rhapsody\"",
    "111": "\"Chocolate River\""
}
